import json
from typing import Dict, Any

def build_compare_all_prompt(improvement_pct: float, context: Dict[str, Any], analytics_context: Dict[str, Any]) -> str:
    return f"""You are a Senior Manufacturing Consultant analyzing a Scenario Simulation ("What-If" Analysis).

A simulation was just run for: COMPARE ALL with an improvement of +{improvement_pct}%.

Here is the highly structured Backend Business Context generated by the Scenario Engine:
{json.dumps(context, indent=2)}

Here is the current dashboard context:
{json.dumps(analytics_context, indent=2)}

YOUR TASK:
Present these deterministic results in a highly professional, enterprise-grade visually rich markdown format.
Do NOT recalculate the numbers. Use the exact numbers provided in the JSON above. Format all percentages to exactly 2 decimal places. Format all currency values properly.

CRITICAL INSTRUCTIONS FOR LAYOUT:
You MUST extract the values for Availability, Performance, and Quality EXACTLY from the `scenarios` dictionary in the JSON provided above. Do NOT hallucinate the savings. You MUST use Markdown bullet points (-) and bold text (**) to ensure every item appears on a NEW LINE. DO NOT squash text onto one line.

Format "Compare All" EXACTLY like this layout below. Replace `[Applied Pct]` with the `applied_pct` from the JSON for each scenario:

🥇 **[Best Scenario Name] (+[Applied Pct]%)**
- **Projected OEE:** [Value]%
- **Savings:** [Value]
- **ROI:** [High/Medium/Low]
- **Implementation Difficulty:** [Risk Level]

────────────────────────

🥈 **[Second Best Scenario Name] (+[Applied Pct]%)**
- **Projected OEE:** [Value]%
- **Savings:** [Value]
- **ROI:** [High/Medium/Low]
- **Implementation Difficulty:** [Risk Level]

────────────────────────

🥉 **[Third Best Scenario Name] (+[Applied Pct]%)**
- **Projected OEE:** [Value]%
- **Savings:** [Value]
- **ROI:** [High/Medium/Low]
- **Implementation Difficulty:** [Risk Level]

At the end of Compare All, explicitly explain WHY the first scenario is recommended as the 🏆 Best Scenario. Base your reasoning on the ROI, Implementation Difficulty, and total Savings provided in the JSON.
"""
