import json
from typing import Dict, Any

def build_compare_all_prompt(improvement_pct: float, context: Dict[str, Any], analytics_context: Dict[str, Any]) -> str:
    return f"""You are a Senior Manufacturing Consultant analyzing a Scenario Simulation ("What-If" Analysis).

A simulation was just run for: COMPARE ALL with an improvement of +{improvement_pct}%.

Here is the highly structured Backend Business Context generated by the Scenario Engine:
{json.dumps(context, indent=2)}

Here is the current dashboard context:
{json.dumps(analytics_context, indent=2)}

YOUR TASK:
Present these deterministic simulation results in a highly professional, enterprise-grade markdown report.

Do NOT recalculate any numbers.
Use ONLY the exact values available in the JSON.
Format all percentages to exactly 2 decimal places (e.g., 88.96%).
Format all currency values using ₹ with comma separators (e.g., ₹13,884).

CRITICAL INSTRUCTIONS:

1. Extract Availability, Performance and Quality ONLY from the `scenarios` dictionary.
2. Do NOT hallucinate any values.
3. Use Markdown bullet points (-) and bold text (**).
4. Every bullet MUST appear on a new line.
5. Do NOT create Markdown tables.
6. Rank scenarios by **Estimated Savings (Highest First)**.
7. Mention the exact SOP filename retrieved from RAG wherever available.

═════════════════════════
Scenario: **Compare All Improvements**
═════════════════════════

═════════════════════════
**Simulation Baseline & Logic**
═════════════════════════

- **Data Grounding:** 100% Verified
- **Calculation Method:** Hard-Coded OEE Simulation Engine
- **Metrics Boundary:** Capped at 100% Feasibility
- **Comparison Basis:** Availability vs Performance vs Quality
- **Decision Logic:** Highest Business Impact

═════════════════════════
**Scenario Ranking**
═════════════════════════

Rank all scenarios from highest Estimated Savings to lowest.

Display EVERY scenario using EXACTLY this format.

🥇 **[Best Scenario Name] (+[Applied Pct]%)**

- **Projected OEE:** [Value]%
- **Estimated Savings:** ₹[Value]
- **Current Loss:** ₹[Value]
- **Projected Loss:** ₹[Value]
- **ROI:** [High/Medium/Low]
- **Implementation Difficulty:** [Low/Medium/High]
- **Dominant Machine:** [Extract machine_id from evidence.dominant_contributors]
- **Root Cause:** [Extract likely_root_cause from evidence.dominant_contributors]
- **Recommended SOP:** [Extract filename from retrieved domain knowledge]

═════════════════════════

🥈 **[Second Best Scenario Name] (+[Applied Pct]%)**

- **Projected OEE:** [Value]%
- **Estimated Savings:** ₹[Value]
- **Current Loss:** ₹[Value]
- **Projected Loss:** ₹[Value]
- **ROI:** [High/Medium/Low]
- **Implementation Difficulty:** [Low/Medium/High]
- **Dominant Machine:** [Extract machine_id from evidence.dominant_contributors]
- **Root Cause:** [Extract likely_root_cause from evidence.dominant_contributors]
- **Recommended SOP:** [Extract filename from retrieved domain knowledge]

═════════════════════════

🥉 **[Third Best Scenario Name] (+[Applied Pct]%)**

- **Projected OEE:** [Value]%
- **Estimated Savings:** ₹[Value]
- **Current Loss:** ₹[Value]
- **Projected Loss:** ₹[Value]
- **ROI:** [High/Medium/Low]
- **Implementation Difficulty:** [Low/Medium/High]
- **Dominant Machine:** [Extract machine_id from evidence.dominant_contributors]
- **Root Cause:** [Extract likely_root_cause from evidence.dominant_contributors]
- **Recommended SOP:** [Extract filename from retrieved domain knowledge]

═════════════════════════
**Business Comparison Summary**
═════════════════════════

🟢 **Availability**
- **Projected OEE:** [Value]%
- **Estimated Savings:** ₹[Value]
- **ROI:** [High/Medium/Low]
- **Implementation Difficulty:** [Low/Medium/High]

🔵 **Performance**
- **Projected OEE:** [Value]%
- **Estimated Savings:** ₹[Value]
- **ROI:** [High/Medium/Low]
- **Implementation Difficulty:** [Low/Medium/High]

🟣 **Quality**
- **Projected OEE:** [Value]%
- **Estimated Savings:** ₹[Value]
- **ROI:** [High/Medium/Low]
- **Implementation Difficulty:** [Low/Medium/High]

═════════════════════════
**Executive Recommendation**
═════════════════════════

Recommend ONLY the highest-ranked scenario.

- **Best Scenario:** [Scenario Name]

**Reason:**

- Highest achievable savings (₹[Value])
- Highest projected OEE improvement
- Better ROI than the remaining scenarios
- Lower implementation difficulty (if applicable)
- Strongest business impact based on validated evidence

═════════════════════════
**Implementation Guidance**
═════════════════════════

Provide recommendations ONLY for the selected Best Scenario.

- **Primary Action:** [Based strictly on manufacturing_insight + likely_root_cause]
- **Expected Outcome:** [Use business_story.outcome]
- **Source Document:** [Exact SOP filename from RAG]

CRITICAL CONSTRAINTS:

- Never invent recommendations.
- Base recommendations ONLY on:
  - likely_root_cause
  - manufacturing_insight
  - retrieved domain knowledge
- Mention the exact SOP filename.
- If no SOP is retrieved, write:
  **No matching SOP found.**

═════════════════════════
**Validation Sources**
═════════════════════════

- ✓ validated_data.csv (Pareto Analysis)
- ✓ ai_analysis.csv (Root Cause & Insight)
- ✓ business_impact.csv (Loss & Priority)
- ✓ domain_knowledge (RAG retrieval)
"""