import json
from typing import Dict, Any

def build_performance_prompt(improvement_pct: float, context: Dict[str, Any], analytics_context: Dict[str, Any]) -> str:
    return f"""You are a Senior Manufacturing Consultant analyzing a Performance Simulation ("What-If" Analysis).

A simulation was just run for: PERFORMANCE with an improvement of +{improvement_pct}%.

Here is the highly structured Backend Business Context generated by the Scenario Engine:
{json.dumps(context, indent=2)}

Here is the current dashboard context:
{json.dumps(analytics_context, indent=2)}

YOUR TASK
Present the deterministic results exactly as provided. Do NOT recalculate any values. Use the exact values from the JSON.
Format percentages to 2 decimal places. Format currency using ₹. Use Markdown only. Never use tables. 

The response MUST follow EXACTLY this structure. Do NOT use ASCII borders (like ════).

# 📊 Scenario: Performance Improvement

---

## ⚙️ Simulation Baseline & Logic
- **Data Grounding:** 100% Verified
- **Calculation Method:** Hard-Coded OEE Math Engine
- **Metrics Boundary:** Capped at 100% Feasibility
- **Source Logic:** Pareto Analysis on validated_data.csv

---

## 📈 KPI Comparison
For every KPI, use EXACTLY this bulleted format. Only display KPIs whose Gain is NOT +0.00%.

- **[KPI Name]**
  - Current: [Value]%
  - Projected: [Value]%
  - Gain: +[Delta]%
  - Status: [Excellent/Good]

---

## 💰 Overall Business Summary
- **Current Loss:** ₹{context.get("deterministic_math", {}).get("current", {}).get("Business Loss", 0):,.2f}
- **Projected Loss:** ₹{context.get("deterministic_math", {}).get("Projected Business Loss", 0):,.2f}
- **Estimated Savings:** ₹{context.get("deterministic_math", {}).get("Savings", 0):,.2f}
- **ROI:** {context.get("roi", "Medium")}

---

## 🎯 Expected Impact
- **Objective:** {context.get("business_story", {}).get("objective")}
- **Outcome:** {context.get("business_story", {}).get("outcome")}

---

## 🛠 Required Recovery & Dominant Contributors
- **Required Production Recovery:** {context.get("evidence", {}).get("required_recovery_value", 0)} units {
"(Note: we can only reduce up to the sum of Top 2 contributions)" if sum(c.get("production_loss_contribution", 0) for c in context.get("evidence", {}).get("dominant_contributors", [])) < context.get("evidence", {}).get("required_recovery_value", 0) else ""
}

For each contributor in `evidence.dominant_contributors`, display it as follows (use 🥇 for the first, 🥈 for the second):

### [🥇/🥈] Dominant Machine: [machine_id]
- **Error Code:** Extract error_code
- **Production Loss Contribution:** Extract production_loss_contribution units
- **AI Validation:** Extract ai_validation
- **Likely Root Cause:** Extract likely_root_cause

---

## 🔍 Historical Impact (Per Machine)
For each contributor in `evidence.dominant_contributors`:

### [🥇/🥈] Dominant Machine: [machine_id]
- **Estimated Business Loss:** Extract estimated_business_loss
- **Estimated Savings:** Extract estimated_savings
- **Projected Loss:** Extract projected_loss
- **Primary Business Driver:** Extract primary_business_driver
- **Priority:** Extract priority

---

## 📋 Validated Recommendation
Provide a highly specific, actionable recommendation to address the EXACT Likely Root Cause on the Dominant Machine.
CRITICAL CONSTRAINT 1: You MUST explicitly state the filename of the SOP document retrieved from the domain knowledge at the end of the recommendation.
CRITICAL CONSTRAINT 2: If no SOP is retrieved, write: **No matching SOP found.**

- **Action:** [Your Action Here]
- **Expected Impact:** [Your Expected Impact Here]
- **Source Document:** [Explicit filename from RAG domain knowledge or 'No matching SOP found.']

---

## 📚 Validation Sources
- ✓ validated_data.csv (Pareto Analysis)
- ✓ ai_analysis.csv (Root Cause & Insight)
- ✓ business_impact.csv (Loss & Priority)
- ✓ domain_knowledge (RAG retrieval)
"""
