import json
from typing import Dict, Any

def build_quality_prompt(improvement_pct: float, context: Dict[str, Any], analytics_context: Dict[str, Any]) -> str:
    return f"""You are a Senior Manufacturing Consultant analyzing a Quality Simulation ("What-If" Analysis).

A simulation was just run for: QUALITY with an improvement of +{improvement_pct}%.

Here is the highly structured Backend Business Context generated by the Scenario Engine:
{json.dumps(context, indent=2)}

Here is the current dashboard context:
{json.dumps(analytics_context, indent=2)}

YOUR TASK:
Present these deterministic results in a highly professional, enterprise-grade visually rich markdown format.
Do NOT recalculate the numbers. Use the exact numbers provided in the JSON above. Format all percentages to exactly 2 decimal places. Format all currency values properly.

CRITICAL INSTRUCTIONS FOR LAYOUT:
You MUST format your response using EXACTLY this layout and sectioning, using the exact ASCII separators. You MUST use Markdown bullet points (-) and bold text (**) to ensure every item appears on a NEW LINE. DO NOT squash text onto one line.

══════════════════════
📊 Scenario
**Quality Improvement**
══════════════════════

══════════════════════
🟡 Simulation Confidence
══════════════════════
- **Confidence:** {context.get("confidence", "96%")}
- **Based on:**
  - ✓ Current Dashboard
  - ✓ OEE Model
  - ✓ Business Impact Model

══════════════════════
📈 KPI Comparison
══════════════════════
For every changed KPI, display it exactly like this Rich Card (use bullet points):
- **[KPI Name]**
  - Current: [Value]%
  - ⬆ Projected: [Value]%
  - Gain: +[Delta]%
  - Status: [Excellent/Good]
*Ensure you show Availability, Performance, Quality, and OEE.*

══════════════════════
💰 Business Summary
══════════════════════
- **Current Loss:** [Value]
- **Projected Loss:** [Value]
- **Estimated Savings:** [Value]
- **ROI:** {context.get("roi", "Medium")}
- **Priority:** ⭐⭐⭐⭐⭐

══════════════════════
🎯 Expected Impact
══════════════════════
Explain WHY the numbers changed. Use the business story provided:
- **Objective:** {context.get("business_story", {}).get("objective")}
- **Outcome:** {context.get("business_story", {}).get("outcome")}

══════════════════════
🛠 Recommended Actions
══════════════════════
Provide 3 highly specific, actionable recommendations.
CRITICAL CONSTRAINT: {context.get("recommendation_style", "Focus on defects.")}
State WHY each recommendation helps and what the expected benefit is.
Example:
- **Action:** Defect Analysis
  - **Expected Benefit:** Reduce scrap and rework
  - **Estimated Gain:** 1-2%

══════════════════════
⚠️ Risk Assessment
══════════════════════
- **Operational Risk:** {context.get("risk_assessment", {}).get("Operational Risk", "Low")}
- **Implementation Risk:** {context.get("risk_assessment", {}).get("Implementation Risk", "High")}
- **Expected Downtime During Rollout:** {context.get("risk_assessment", {}).get("Expected Downtime During Rollout", "0")}

══════════════════════
⚙️ Implementation Roadmap
══════════════════════
- **Week 1:** {context.get("roadmap", {}).get("Week 1", "")}
- **Week 2:** {context.get("roadmap", {}).get("Week 2", "")}
- **Week 3:** {context.get("roadmap", {}).get("Week 3", "")}
- **Week 4:** {context.get("roadmap", {}).get("Week 4", "")}

══════════════════════
🔥 Action Priority
══════════════════════
- 🔴 **Immediate:** {context.get("priorities", {}).get("Immediate", "")}
- 🟠 **Within 1 Week:** {context.get("priorities", {}).get("Within 1 Week", "")}
- 🟢 **Long Term:** {context.get("priorities", {}).get("Long Term", "")}

══════════════════════
📌 Assumptions
══════════════════════
- ✓ Demand remains unchanged
- ✓ Only Quality is modified
- ✓ Availability remains constant
- ✓ Performance remains constant
"""
